kind: pipeline
name: default

steps:
- name: install
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle install --jobs=3 --retry=3

- name: lint
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

- name: test
  image: ruby:2.6
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rspec

volumes:
- name: bundle
  temp: {}
