name: Run Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install bundler
        run: gem install bundler
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: prime-multiplier-v1-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: prime-multiplier-v1-${{ runner.os }}-
      - name: Setup bundler path
        run: bundle config path vendor/bundle
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2.2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install bundler
        run: gem install bundler
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: prime-multiplier-v1-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: prime-multiplier-v1-${{ runner.os }}-
      - name: Setup bundler path
        run: bundle config path vendor/bundle
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Run Specs
        run: bundle exec rspec
